"""Fixed inputs for the independently reviewed workflow graph snapshots."""

from h3_app.model_types import ModelConfig, ModelProfile

MODELS = ModelConfig(
    profiles={
        "speed": ModelProfile(
            label="Speed",
            fl2va="fl2va_speed.safetensors",
            ref2va="ref2va_speed.safetensors",
        ),
        "quality": ModelProfile(
            label="Quality",
            fl2va="fl2va_quality_convrot.safetensors",
            ref2va="ref2va_quality_convrot.safetensors",
        ),
        "original": ModelProfile(
            label="Original",
            fl2va="minimax_h3_fl2va_pruned_bf16.safetensors",
            ref2va="minimax_h3_ref2va_pruned_bf16.safetensors",
        ),
    },
    default_profile="speed",
    text_encoder="text.safetensors",
    video_vae="video_vae.safetensors",
    audio_vae="audio_vae.safetensors",
    video_vae_int8="video_vae_int8_convrot.safetensors",
    video_vae_int8_source="test",
    video_vae_trt_encoder="minimax_h3_vae_encoder.onnx",
    video_vae_trt_decoder="minimax_h3_vae_decoder.onnx",
    video_vae_trt_source="test",
    image_vae_500k="minimax_h3_single_frame_decoder_500k.safetensors",
    image_vae_500k_source="test",
    turbo_lora="minimax_h3_fl2v_turbo_4step_v1.2_768p_comfyui_bf16.safetensors",
    turbo_source="test",
    turbo_ref_lora="minimax_h3_ref2v_turbo_4step_v0.1_comfyui_bf16.safetensors",
    turbo_ref_source="ref2v-test",
    turbo_8step_lora="minimax_h3_fl2v_turbo_8step_v1.0_768p_comfyui_bf16.safetensors",
    turbo_8step_source="test",
    turbo_8step_ref_lora="minimax_h3_ref2v_turbo_8step_v1.0_768p_comfyui_bf16.safetensors",
    turbo_8step_ref_source="ref2v-test",
    larry_turbo_lora="minimax_h3_turbo_v4_step600_ema.safetensors",
    larry_turbo_source="test",
    larry_turbo_ref_lora="minimax_h3_turbo_v4_step600_ema.safetensors",
    larry_turbo_ref_source="shared-fl2va-test",
    seedvr2_dit="seedvr2_7b_nvfp4.safetensors",
    seedvr2_dit_source="test",
    seedvr2_models={
        "3B NVFP4": "seedvr2_3b_nvfp4.safetensors",
        "3B INT8": "seedvr2_3b_int8_convrot.safetensors",
        "7B NVFP4": "seedvr2_7b_nvfp4.safetensors",
        "7B Sharp NVFP4": "seedvr2_7b_sharp_nvfp4.safetensors",
    },
    seedvr2_vae="seedvr2_ema_vae_fp16.safetensors",
    seedvr2_vae_source="test",
)

AVAILABLE_NODES = {
    "BasicGuider",
    "BasicScheduler",
    "CLIPLoader",
    "CreateVideo",
    "EasyCache",
    "GetVideoComponents",
    "H3CombineAVLatent",
    "H3ConditioningCache",
    "H3FirstBlockCache",
    "H3LightX2VBypassLoRA",
    "H3RefinementCompilerGuard",
    "H3SLAAttention",
    "H3SaveVideoNVENC",
    "H3SeparateAVLatent",
    "H3SingleFrameVAELoader",
    "H3StageModelOffload",
    "H3StageOffloadPolicy",
    "H3VideoLatentSlicesToBatch",
    "KSamplerSelect",
    "LoadAudio",
    "LoadImage",
    "LoadVideo",
    "MMH3SpatialSplitParamsV10",
    "MMH3SplitUpscale",
    "MMH3TemporalSplitParamsV10",
    "MiniMaxH3ChunkFeedForward",
    "MiniMaxH3FusedModulation",
    "MiniMaxH3ImageToVideo",
    "MiniMaxH3MemoryEfficientSolAttentionPatch",
    "MiniMaxH3ReferenceToVideo",
    "MiniMaxH3SigmaShift",
    "MiniMaxH3TurboLoRA",
    "MiniMaxH3TurboSampler",
    "MinimaxH3LatentUpscaler3D",
    "PathchSageAttentionKJ",
    "RandomNoise",
    "SamplerCustomAdvanced",
    "SpectrumApplyMiniMaxH3",
    "SplitSigmas",
    "UNETLoader",
    "VAEDecode",
    "VAEDecodeAudio",
    "VAELoader",
}

H3_DEFAULTS = {
    "prompt": "test",
    "first_image": None,
    "last_image": None,
    "width": 864,
    "height": 480,
    "duration": 5,
    "steps": 4,
    "seed": 2,
    "scheduler": "simple",
    "turbo_lora_name": None,
    "turbo_variant": "LightX2V / 4-step (FL2V 768p · Ref2V 544p)",
    "turbo_strength": 1.0,
    "use_sol": False,
    "sol_tau": 1.0,
    "sol_thresh_type": "diag",
    "sol_exact_mode": "off",
    "sol_dense_steps": 0,
    "sol_step_off": 0.0,
    "sol_sink_tokens": 0,
    "cache_mode": "Off",
    "fbcache_preset": "Fast",
    "fbcache_threshold": 0.1,
    "fbcache_start": 0.1,
    "fbcache_end": 0.95,
    "fbcache_max_hits": 2,
    "fbcache_temporal_guard": True,
    "easycache_threshold": 0.1,
    "easycache_start": 0.15,
    "easycache_end": 0.85,
    "easycache_verbose": False,
    "model_name": "fl2va_speed.safetensors",
    "models": MODELS,
    "available_nodes": AVAILABLE_NODES,
    "use_lynnreal_vae": False,
    "use_int8_vae": False,
    "use_trt_vae": False,
    "use_sage": False,
    "use_sla": False,
    "sla_preset": "Balanced",
    "latent_upscale_model_name": None,
    "latent_upscale_precision": "bf16",
    "latent_upscale_refine_steps": 2,
    "refinement_lora_name": None,
    "refinement_variant": None,
    "latent_split_config": None,
    "result_format": "Video",
    "image_frames": 5,
    "image_vae": "Official video VAE",
    "text_encoder_name": None,
    "encoder_small_input": True,
    "reuse_unchanged_inputs": True,
    "stage_model_offload": False,
    "smart_stage_offload": False,
    "semantic_bridge": False,
    "semantic_bridge_alpha": 0.1,
    "voice_reference_audios": [],
    "output_stamp": "123",
}

# Each case corresponds to the same row in fixtures/workflow_graphs.json.
CASES = [
    (
        "build_music3_graph",
        {
            "model_choice": "INT8 ConvRot (lower VRAM)",
            "caption": "Global Metadata: test song",
            "lyrics": "[Instrumental]",
            "max_duration": 30,
            "seed": 7,
            "steps": 30,
            "cfg": 1.7,
            "ar_cfg": 1.7,
            "top_k": 50,
            "tiled_decode": True,
        },
    ),
    (
        "build_fl2va_graph",
        {
            **H3_DEFAULTS,
            "steps": 18,
            "seed": 1,
            "turbo_lora_name": "minimax_h3_turbo_4step_ema_ckpt850.safetensors",
            "use_sol": True,
            "sol_thresh_type": "exact",
            "sol_exact_mode": "exact_kv_and_rows",
            "sol_dense_steps": 1,
            "cache_mode": "FirstBlockCache",
            "text_encoder_name": "qwen3vl_32b_minimax_h3_bf16.safetensors",
            "stage_model_offload": True,
            "smart_stage_offload": True,
            "output_nonce": "abc",
        },
    ),
    (
        "build_fl2va_graph",
        {
            **H3_DEFAULTS,
            "prompt": "image result test",
            "result_format": "Image",
            "image_frames": 20,
            "output_nonce": "abc",
        },
    ),
    (
        "build_fl2va_graph",
        {
            **H3_DEFAULTS,
            "prompt": "single-frame image result test",
            "seed": 3,
            "result_format": "Image",
            "image_frames": 1,
            "image_vae": "Single-frame 500K (experimental)",
            "output_nonce": "abc",
        },
    ),
    (
        "build_fl2va_graph",
        {
            **H3_DEFAULTS,
            "prompt": "latent upscale test",
            "width": 1024,
            "height": 1024,
            "steps": 8,
            "scheduler": "beta",
            "turbo_variant": "LightX2V v1.0 / 8-step 768p",
            "latent_upscale_model_name": "minimax_h3_latent_upscaler_3d_bf16.safetensors",
            "stage_model_offload": True,
            "output_nonce": "abc",
        },
    ),
    (
        "build_ltx25_graph",
        {
            "model_choice": "INT8 ConvRot",
            "prompt": "a test shot",
            "negative_prompt": "artifacts",
            "first_image": None,
            "width": 960,
            "height": 544,
            "duration": 5,
            "fps": 24,
            "seed": 9,
            "cfg": 1.0,
            "sampler_name": "euler_ancestral",
            "image_strength": 0.7,
            "middle_image": None,
            "middle_time": 2.5,
            "middle_strength": 0.7,
            "end_image": None,
            "end_strength": 0.7,
            "reference_sheet": None,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_ltx25_graph",
        {
            "model_choice": "INT8 ConvRot",
            "prompt": "a guided test shot",
            "negative_prompt": "artifacts",
            "first_image": "ltx25_keyframes/start.png",
            "width": 960,
            "height": 544,
            "duration": 5,
            "fps": 24,
            "seed": 10,
            "cfg": 1.0,
            "sampler_name": "euler_ancestral",
            "image_strength": 0.8,
            "middle_image": "ltx25_keyframes/middle.png",
            "middle_time": 2.5,
            "middle_strength": 0.65,
            "end_image": "ltx25_keyframes/end.png",
            "end_strength": 0.9,
            "reference_sheet": None,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_seedvr2_upscale_graph",
        {
            "source_video": "h3_gradio/seedvr2_upscale/source.mp4",
            "seed": 7,
            "models": MODELS,
            "model_choice": "7B INT8",
            "target_width": None,
            "source_width": None,
            "fps": 48.0,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_seedvr2_upscale_graph",
        {
            "source_video": "source.mp4",
            "seed": 7,
            "models": MODELS,
            "model_choice": "3B NVFP4",
            "target_width": None,
            "source_width": None,
            "fps": 24.0,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_seedvr2_upscale_graph",
        {
            "source_video": "source.mp4",
            "seed": 7,
            "models": MODELS,
            "model_choice": "3B INT8",
            "target_width": None,
            "source_width": None,
            "fps": 24.0,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_seedvr2_upscale_graph",
        {
            "source_video": "source.mp4",
            "seed": 7,
            "models": MODELS,
            "model_choice": "7B NVFP4",
            "target_width": None,
            "source_width": None,
            "fps": 24.0,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_seedvr2_upscale_graph",
        {
            "source_video": "source.mp4",
            "seed": 7,
            "models": MODELS,
            "model_choice": "7B Sharp NVFP4",
            "target_width": None,
            "source_width": None,
            "fps": 24.0,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_seedvr2_image_upscale_graph",
        {
            "source_images": [
                ["first", "h3_gradio/input_image_upscale/first.png", 2.5],
                ["picture_2", "h3_gradio/input_image_upscale/picture.png", 1.25],
            ],
            "seed": 7,
            "models": MODELS,
            "model_choice": "7B INT8",
            "output_token": "inputtest",
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_ltx25_upscale_graph",
        {
            "source_video": "h3_gradio/ltx25_upscale/source.mp4",
            "seed": 11,
            "model_choice": "INT8 ConvRot",
            "prompt": "a detailed test scene",
            "width": 864,
            "height": 480,
            "target_width": None,
            "target_height": None,
            "fps": 24.0,
            "output_stamp": "123",
            "output_nonce": "abc",
        },
    ),
    (
        "build_fl2va_graph",
        {
            **H3_DEFAULTS,
            "turbo_lora_name": "minimax_h3_fl2v_turbo_4step_v1.2_768p_comfyui_bf16.safetensors",
            "sol_dense_steps": 1,
            "cache_mode": "Spectrum",
            "model_name": "fl2va_quality_convrot.safetensors",
            "use_int8_vae": True,
            "output_nonce": "abc",
        },
    ),
]


STACK_DEFAULTS = {
    field: H3_DEFAULTS[field]
    for field in (
        "turbo_lora_name",
        "turbo_variant",
        "turbo_strength",
        "use_sol",
        "sol_tau",
        "sol_thresh_type",
        "sol_exact_mode",
        "sol_dense_steps",
        "sol_step_off",
        "sol_sink_tokens",
        "cache_mode",
        "fbcache_preset",
        "fbcache_threshold",
        "fbcache_start",
        "fbcache_end",
        "fbcache_max_hits",
        "fbcache_temporal_guard",
        "easycache_threshold",
        "easycache_start",
        "easycache_end",
        "easycache_verbose",
        "available_nodes",
    )
}


def model_stack(graph, model_name, models, **overrides):
    from h3_app.workflows.h3 import add_model_stack

    return add_model_stack(graph, model_name, models, **(STACK_DEFAULTS | overrides))
