"""Application event graph separated from view composition."""

from __future__ import annotations

from typing import Any, Mapping

import gradio as gr


def bind_app(
    components: Mapping[str, Any],
    services: Mapping[str, Any],
) -> None:
    settings_inputs = [
        components["mode"],
        components["model_profile"],
        components["text_encoder"],
        components["stage_model_offload"],
        components["reuse_unchanged_inputs"],
        components["use_int8_vae"],
        components["generation_mode"],
        components["turbo_variant"],
        components["duration"],
        components["width"],
        components["height"],
        components["steps"],
        components["scheduler"],
        components["attention_mode"],
        components["sla_preset"],
        components["cache_mode"],
        components["latent_upscale"],
        components["latent_upscaler_model"],
        components["latent_upscale_refine_steps"],
        components["generation_postprocess"],
        components["generation_seedvr2_model"],
        components["ltx25_model"],
        components["generation_force_offload"],
        components["generation_split_upscale"],
        components["generation_split_seconds"],
        components["result_format"],
        components["image_frames"],
        components["image_vae"],
        components["latent_upscale_method"],
        components["latent_split_tile_width"],
        components["latent_split_tile_height"],
        components["latent_split_overlap_ratio"],
        components["latent_split_fade_ratio"],
        components["latent_split_chunk_frames"],
        components["latent_split_temporal_overlap_frames"],
        components["latent_split_seam_denoise"],
        components["latent_split_seam_polish"],
        components["use_trt_vae"],
    ]
    preflight_inputs = [
        components["mode"],
        components["prompt"],
        components["first"],
        components["last"],
        components["ref_image_1"],
        components["ref_image_2"],
        components["ref_image_3"],
        components["ref_image_4"],
        components["ref_image_5"],
        components["ref_image_6"],
        components["ref_image_7"],
        components["ref_image_8"],
        components["ref_image_9"],
        components["ref_video_1"],
        components["ref_video_2"],
        components["ref_video_3"],
        components["ref_audio_1"],
        components["ref_audio_2"],
        components["ref_audio_3"],
    ]
    services["bind_preflight"](
        preflight_inputs,
        prompt=components["prompt"],
        callback=services["generation_preflight"],
        readiness=components["generation_readiness"],
        primary_action=components["run"],
    )
    services["bind_summary"](
        settings_inputs,
        callback=services["compact_settings_summary"],
        output=components["settings_overview"],
        skip=(components["width"], components["height"]),
    )
    components["mode"].change(
        services["mode_layout_updates"],
        inputs=components["mode"],
        outputs=[
            components["help_text"],
            components["frame_group"],
            components["reference_group"],
            components["generation_mode"],
            components["preset"],
            components["steps"],
            components["scheduler"],
            components["cache_mode"],
            components["attention_mode"],
        ],
    )
    components["text_encoder"].change(
        services["text_encoder_offload_update"],
        inputs=components["text_encoder"],
        outputs=components["stage_model_offload"],
        queue=False,
        show_progress="hidden",
    )
    components["result_format"].change(
        services["result_format_layout_updates"],
        inputs=[
            components["result_format"],
            components["width"],
            components["height"],
            components["first"],
            components["latent_upscale"],
        ],
        outputs=[
            components["duration"],
            components["image_frames"],
            components["image_vae"],
            components["output"],
            components["output_2"],
            components["output_3"],
            components["output_4"],
            components["batch_count"],
            components["image_output_group"],
            components["audio_output"],
            components["generation_postprocess"],
            components["latent_upscale"],
            components["width"],
            components["height"],
            components["resolution_info"],
            components["run"],
        ],
        queue=False,
        show_progress="hidden",
    )
    components["image_vae"].change(
        services["image_vae_frame_updates"],
        inputs=components["image_vae"],
        outputs=components["image_frames"],
        queue=False,
        show_progress="hidden",
    )
    components["latent_upscale"].change(
        services["latent_upscale_layout_updates"],
        inputs=[
            components["latent_upscale"],
            components["width"],
            components["height"],
            components["result_format"],
        ],
        outputs=[
            components["latent_upscale_settings"],
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
    )
    components["latent_upscale_method"].change(
        services["latent_upscale_method_layout_update"],
        inputs=components["latent_upscale_method"],
        outputs=components["latent_split_settings"],
        queue=False,
        show_progress="hidden",
    )
    ltx25_event = services["bind_ltx_view"](
        components["ltx25_components"],
        render_workflow=services["render_ltx25_workflow_details"],
        prepare_workflow=services["prepare_ltx25_official_workflow"],
        prepare_all_models=services["prepare_all_ltx25_official_models"],
        render_inventory=services["render_ltx25_official_model_inventory"],
        enhance_prompt=services["enhance_ltx25_prompt"],
        generate=services["generate_ltx25"],
    )
    components["generation_postprocess"].change(
        lambda value: (
            gr.update(visible=value in services["AI_POSTPROCESS_OPTIONS"]),
            gr.update(visible=value == services["SEEDVR2_UPSCALE"]),
            gr.update(visible=value == services["LTX25_UPSCALE"]),
            gr.update(visible=value == services["LTX25_UPSCALE"]),
            gr.update(visible=value == services["LTX25_UPSCALE"]),
        ),
        inputs=components["generation_postprocess"],
        outputs=[
            components["generation_postprocess_settings"],
            components["generation_seedvr2_model"],
            components["generation_ltx25_note"],
            components["generation_split_upscale"],
            components["generation_split_seconds"],
        ],
        queue=False,
        show_progress="hidden",
    )
    components["generation_mode"].change(
        services["generation_mode_defaults"],
        inputs=[components["generation_mode"], components["turbo_variant"]],
        outputs=[
            components["preset"],
            components["steps"],
            components["scheduler"],
            components["cache_mode"],
            components["attention_mode"],
        ],
        queue=False,
        show_progress="hidden",
    )
    components["turbo_variant"].change(
        services["turbo_variant_defaults"],
        inputs=[components["turbo_variant"], components["generation_mode"]],
        outputs=[components["steps"], components["scheduler"]],
        queue=False,
        show_progress="hidden",
    )
    components["preset"].change(
        services["preset_values"],
        inputs=[components["preset"], components["generation_mode"]],
        outputs=[
            components["steps"],
            components["sol_tau"],
            components["sol_thresh_type"],
            components["scheduler"],
            components["sol_exact_mode"],
            components["sol_dense_steps"],
            components["auto_megapixels"],
            components["turbo_variant"],
            components["attention_mode"],
            components["sla_preset"],
            components["latent_upscale_refine_steps"],
            components["text_encoder"],
            components["stage_model_offload"],
        ],
    )
    draft_resolution_event = components["draft_resolution"].change(
        lambda name: services["resolution_choice_values"](name, "draft"),
        inputs=components["draft_resolution"],
        outputs=[
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
    )
    fast_resolution_event = components["fast_resolution"].change(
        lambda name: services["resolution_choice_values"](name, "fast"),
        inputs=components["fast_resolution"],
        outputs=[
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
    )
    large_resolution_event = components["large_resolution"].change(
        lambda name: services["resolution_choice_values"](name, "large"),
        inputs=components["large_resolution"],
        outputs=[
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
    )
    for resolution_event in (
        draft_resolution_event,
        fast_resolution_event,
        large_resolution_event,
    ):
        aligned_resolution_event = resolution_event.then(
            services["resolution_control_updates"],
            inputs=[
                components["width"],
                components["height"],
                components["latent_upscale"],
                components["result_format"],
            ],
            outputs=[
                components["width"],
                components["height"],
                components["resolution_info"],
            ],
            queue=False,
            show_progress="hidden",
        )
        aligned_resolution_event.then(
            services["compact_settings_summary"],
            inputs=settings_inputs,
            outputs=components["settings_overview"],
            queue=False,
            show_progress="hidden",
        )
    components["first"].upload(
        fn=None,
        inputs=[
            components["first"],
            components["width"],
            components["height"],
            components["result_format"],
            components["latent_upscale"],
            components["auto_megapixels"],
        ],
        outputs=[
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
        js=services["AUTO_RESOLUTION_JS"],
        queue=False,
        show_progress="hidden",
    )
    first_change_event = components["first"].change(
        fn=services["auto_resolution_from_start_frame"],
        inputs=[
            components["first"],
            components["width"],
            components["height"],
            components["result_format"],
            components["latent_upscale"],
            components["auto_megapixels"],
        ],
        outputs=[
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
        queue=False,
        show_progress="hidden",
    )
    first_change_event.then(
        services["compact_settings_summary"],
        inputs=settings_inputs,
        outputs=components["settings_overview"],
        queue=False,
        show_progress="hidden",
    )
    auto_megapixels_change = components["auto_megapixels"].change(
        fn=services["auto_resolution_from_start_frame"],
        inputs=[
            components["first"],
            components["width"],
            components["height"],
            components["result_format"],
            components["latent_upscale"],
            components["auto_megapixels"],
        ],
        outputs=[
            components["width"],
            components["height"],
            components["resolution_info"],
        ],
        queue=False,
        show_progress="hidden",
    )
    auto_megapixels_change.then(
        services["compact_settings_summary"],
        inputs=settings_inputs,
        outputs=components["settings_overview"],
        queue=False,
        show_progress="hidden",
    )
    components["fbcache_preset"].change(
        services["fbcache_preset_defaults"],
        inputs=components["fbcache_preset"],
        outputs=[
            components["fbcache_threshold"],
            components["fbcache_start"],
            components["fbcache_end"],
            components["fbcache_max_hits"],
        ],
    )
    components["width"].input(
        services["resolution_info_preview"],
        inputs=[
            components["width"],
            components["height"],
            components["latent_upscale"],
            components["result_format"],
        ],
        outputs=[components["resolution_info"]],
        queue=False,
        show_progress="hidden",
    )
    components["height"].input(
        services["resolution_info_preview"],
        inputs=[
            components["width"],
            components["height"],
            components["latent_upscale"],
            components["result_format"],
        ],
        outputs=[components["resolution_info"]],
        queue=False,
        show_progress="hidden",
    )
    for res_event_trigger in (
        components["width"].blur,
        components["height"].blur,
        components["width"].submit,
        components["height"].submit,
    ):
        res_snap_event = res_event_trigger(
            services["resolution_control_updates"],
            inputs=[
                components["width"],
                components["height"],
                components["latent_upscale"],
                components["result_format"],
            ],
            outputs=[
                components["width"],
                components["height"],
                components["resolution_info"],
            ],
            queue=False,
            show_progress="hidden",
        )
        res_snap_event.then(
            services["compact_settings_summary"],
            inputs=settings_inputs,
            outputs=components["settings_overview"],
            queue=False,
            show_progress="hidden",
        )
    components["input_upscale_frame_preset"].change(
        services["input_image_frame_preset_updates"],
        inputs=[
            components["input_upscale_frame_preset"],
            components["input_upscale_frame_width"],
            components["input_upscale_frame_height"],
        ],
        outputs=[
            components["input_upscale_frame_width"],
            components["input_upscale_frame_height"],
        ],
        queue=False,
        show_progress="hidden",
        api_name=False,
    )
    input_upscale_event = components["input_upscale_run"].click(
        services["upscale_selected_input_images"],
        inputs=[
            components["input_upscale_slots"],
            components["input_upscale_model"],
            components["input_upscale_seed"],
            components["input_upscale_force_offload"],
            components["input_upscale_frame_width"],
            components["input_upscale_frame_height"],
            components["first"],
            components["last"],
            components["ref_image_1"],
            components["ref_image_2"],
            components["ref_image_3"],
            components["ref_image_4"],
            components["ref_image_5"],
            components["ref_image_6"],
            components["ref_image_7"],
            components["ref_image_8"],
            components["ref_image_9"],
        ],
        outputs=[
            components["first"],
            components["last"],
            components["ref_image_1"],
            components["ref_image_2"],
            components["ref_image_3"],
            components["ref_image_4"],
            components["ref_image_5"],
            components["ref_image_6"],
            components["ref_image_7"],
            components["ref_image_8"],
            components["ref_image_9"],
            components["input_upscale_downloads"],
            components["input_upscale_status"],
        ],
        show_progress="minimal",
        api_name="upscale_h3_input_images",
    )
    event = components["run"].click(
        services["generate_for_ui"],
        inputs=[
            components["batch_count"],
            components["mode"],
            components["model_profile"],
            components["text_encoder"],
            components["stage_model_offload"],
            components["generation_mode"],
            components["turbo_variant"],
            components["prompt"],
            components["first"],
            components["last"],
            components["ref_image_1"],
            components["ref_image_2"],
            components["ref_image_3"],
            components["ref_image_4"],
            components["ref_image_5"],
            components["ref_image_6"],
            components["ref_image_7"],
            components["ref_image_8"],
            components["ref_image_9"],
            components["ref_video_1"],
            components["ref_video_2"],
            components["ref_video_3"],
            components["ref_audio_1"],
            components["ref_audio_2"],
            components["ref_audio_3"],
            components["duration"],
            components["width"],
            components["height"],
            components["steps"],
            components["scheduler"],
            components["seed"],
            components["attention_mode"],
            components["sla_preset"],
            components["sol_tau"],
            components["sol_thresh_type"],
            components["sol_exact_mode"],
            components["sol_dense_steps"],
            components["sol_step_off"],
            components["sol_sink_tokens"],
            components["cache_mode"],
            components["fbcache_preset"],
            components["fbcache_threshold"],
            components["fbcache_start"],
            components["fbcache_end"],
            components["fbcache_max_hits"],
            components["fbcache_temporal_guard"],
            components["easycache_threshold"],
            components["easycache_start"],
            components["easycache_end"],
            components["easycache_verbose"],
            components["ref_size"],
            components["generation_postprocess"],
            components["reuse_unchanged_inputs"],
            components["latent_upscale"],
            components["latent_upscaler_model"],
            components["latent_upscale_refine_steps"],
            components["latent_upscale_method"],
            components["latent_split_tile_width"],
            components["latent_split_tile_height"],
            components["latent_split_overlap_ratio"],
            components["latent_split_fade_ratio"],
            components["latent_split_chunk_frames"],
            components["latent_split_temporal_overlap_frames"],
            components["latent_split_seam_denoise"],
            components["latent_split_seam_polish"],
            components["generation_force_offload"],
            components["generation_split_upscale"],
            components["generation_split_seconds"],
            components["generation_upscale_resolution"],
            components["generation_seedvr2_model"],
            components["ltx25_model"],
            components["use_int8_vae"],
            components["use_trt_vae"],
            components["image_vae"],
            components["result_format"],
            components["image_frames"],
        ],
        outputs=[
            components["output"],
            components["output_2"],
            components["output_3"],
            components["output_4"],
            components["image_output_group"],
            components["image_output"],
            components["image_selection"],
            components["image_frame_paths"],
            components["image_saved_files"],
            components["audio_output"],
            components["image_save_status"],
            components["status"],
        ],
        show_progress="minimal",
        api_name="generate_video_advanced",
    )
    components["image_select_all"].click(
        services["select_all_image_frames"],
        inputs=components["image_frame_paths"],
        outputs=components["image_selection"],
        queue=False,
        show_progress="hidden",
        api_name=False,
    )
    components["image_clear_selection"].click(
        lambda: [],
        outputs=components["image_selection"],
        queue=False,
        show_progress="hidden",
        api_name=False,
    )
    components["image_save_selected"].click(
        services["save_selected_image_frames"],
        inputs=[components["image_frame_paths"], components["image_selection"]],
        outputs=[components["image_saved_files"], components["image_save_status"]],
        show_progress="minimal",
        api_name="save_h3_image_frames",
    )
    components["prompt_writer_backend"].change(
        services["prompt_writer_backend_visibility"],
        inputs=components["prompt_writer_backend"],
        outputs=[
            components["local_prompt_writer_group"],
            components["gemini_prompt_writer_group"],
            components["lightning_prompt_writer_group"],
        ],
        queue=False,
        show_progress="hidden",
        api_name=False,
    )
    components["enhance_prompt_button"].click(
        services["enhance_h3_prompt"],
        inputs=[
            components["prompt"],
            components["prompt_writer_backend"],
            components["local_prompt_base_model"],
            components["local_prompt_max_tokens"],
            components["local_prompt_temperature"],
            components["local_prompt_top_p"],
            components["local_prompt_greedy"],
            components["local_prompt_seed"],
            components["gemini_prompt_model"],
            components["gemini_api_key"],
            components["lightning_api_key"],
            components["mode"],
            components["first"],
            components["last"],
            components["ref_image_1"],
            components["ref_image_2"],
            components["ref_image_3"],
            components["ref_image_4"],
            components["ref_image_5"],
            components["ref_image_6"],
            components["ref_image_7"],
            components["ref_image_8"],
            components["ref_image_9"],
            components["ref_video_1"],
            components["ref_video_2"],
            components["ref_video_3"],
            components["ref_audio_1"],
            components["ref_audio_2"],
            components["ref_audio_3"],
            components["duration"],
            components["width"],
            components["height"],
            components["result_format"],
            components["image_frames"],
        ],
        outputs=[components["prompt"], components["enhance_prompt_status"]],
        show_progress="minimal",
        api_name="enhance_prompt",
    )
    music3_event = services["bind_music_view"](
        components["music3_components"],
        enhance_prompt=services["enhance_music3_prompt"],
        generate=services["generate_music3"],
    )
    api_event = services["bind_api_view"](
        components["api_components"], generate=services["generate_with_ui_defaults"]
    )
    services["bind_interrupts"](
        services["interrupt"],
        [
            (components["stop"], components["status"], [event, input_upscale_event]),
            (components["ltx25_stop"], components["ltx25_status"], [ltx25_event]),
            (components["music3_stop"], components["music3_status"], [music3_event]),
            (components["api_stop"], components["api_status"], [api_event]),
        ],
    )
    components["refresh"].click(
        services["refresh_backend_views"],
        outputs=[components["system_summary"], components["health"]],
        queue=False,
        show_progress="hidden",
    )
    components["unload_models"].click(
        services["unload_all_models"],
        outputs=[components["memory_status"], components["health"]],
        show_progress="minimal",
        api_name=False,
    ).then(
        services["refresh_backend_views"],
        outputs=[components["system_summary"], components["health"]],
        queue=False,
        show_progress="hidden",
    )
    services["bind_gallery_view"](
        components["gallery_components"],
        tab=components["gallery_tab"],
        selected_ltx_model=components["ltx25_model"],
        ai_options=services["AI_POSTPROCESS_OPTIONS"],
        seedvr_option=services["SEEDVR2_UPSCALE"],
        ltx_option=services["LTX25_UPSCALE"],
        refresh=services["refresh_gallery"],
        select=services["select_gallery_video"],
        import_video=services["import_gallery_video"],
        postprocess=services["postprocess_selected_gallery_video"],
        interrupt=services["interrupt"],
        delete=services["delete_selected_gallery_video"],
        empty=services["empty_generated_gallery"],
    )
